apiVersion: v1
kind: ConfigMap
metadata:
  name: jktota-config
  namespace: jktota
data:
  # Database
  POSTGRES_DB: "jktota_db"
  POSTGRES_USER: "jktota"

  # Server
  NODE_ENV: "production"
  SERVER_PORT: "3000"
  SERVER_URL: "http://server:3000"
  CLIENT_URL: "http://client"

  # YouTube Service
  YOUTUBE_SERVICE_PORT: "3001"
  DOWNLOAD_PATH: "/app/downloads"

  # Telegram Bot
  YOUTUBE_SERVICE_URL: "http://youtube-service:3001"
