name: Build & Push Docker Images

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: eu-north-1
  ECR_REGISTRY: 418642192877.dkr.ecr.eu-north-1.amazonaws.com
  ECR_REPOSITORY: all/totaje

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1   # последовательная сборка, чтобы OIDC не дропало jobs
      matrix:
        service:
          - name: server
            path: server
          - name: youtube-service
            path: youtube-service
          - name: client
            path: client
          - name: telegram-bot
            path: telegram-bot

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::418642192877:role/github-actions-ecr
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push ${{ matrix.service.name }}
        run: |
          IMAGE=${ECR_REGISTRY}/${ECR_REPOSITORY}

          docker build \
            -f ${{ matrix.service.path }}/Dockerfile \
            -t $IMAGE:${{ matrix.service.name }}-${{ github.sha }} \
            -t $IMAGE:${{ matrix.service.name }}-latest \
            ${{ matrix.service.path }}

          docker push $IMAGE:${{ matrix.service.name }}-${{ github.sha }}
          docker push $IMAGE:${{ matrix.service.name }}-latest
